-- =============================================================================
-- Volcado inicial: catálogo cliente/intermediario + saldos CC desde Excel
-- GENERADO por scripts/generar-sql-vuelco-inicial.js — no editar a mano; regenerar con:
--   npm run sql:vuelco-inicial
--   VUELCO_USUARIO_EMAIL=... VUELCO_MONEDA_SALDO=USD|ARS|EUR npm run sql:vuelco-inicial
-- Origen: docs/Vuelco_Inicial.xlsx
-- Hoja: primera solapa; A=Cliente, B=Saldo, C=Cliente o Intermediario
-- Convención producto: importes en USD (columna Saldo).
-- Moneda movimientos CC: USD
-- usuario_id: auth.users ← lucas.bustos.martin@gmail.com
-- Pagador/cobrador manual: saldo<0 → pagador entidad + cobrador empresa; saldo>0 → pagador empresa + cobrador entidad.
-- =============================================================================
-- PELIGRO: borra órdenes, transacciones, CC, caja y catálogos cliente/intermediario.
-- Requiere public.fecha_hoy_argentina() y que el usuario exista en Auth.
-- =============================================================================

BEGIN;

-- Borrado previo de saldos de un volcado Excel anterior (mismo texto de concepto).
-- Útil si ajustás el script y no truncás CC; tras TRUNCATE completo no borra filas.
DELETE FROM public.movimientos_cuenta_corriente
  WHERE es_movimiento_manual IS TRUE AND concepto LIKE 'Saldo inicial (volcado Excel)%';
DELETE FROM public.movimientos_cuenta_corriente_intermediario
  WHERE es_movimiento_manual IS TRUE AND concepto LIKE 'Saldo inicial (volcado Excel)%';

TRUNCATE TABLE public.movimientos_cuenta_corriente CASCADE;
TRUNCATE TABLE public.movimientos_cuenta_corriente_intermediario CASCADE;
TRUNCATE TABLE public.movimientos_caja CASCADE;

DO $$ BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'orden_comisiones_generadas') THEN
    EXECUTE 'TRUNCATE TABLE public.orden_comisiones_generadas CASCADE';
  END IF;
END $$;

TRUNCATE TABLE public.transacciones CASCADE;
TRUNCATE TABLE public.comisiones_orden CASCADE;
TRUNCATE TABLE public.instrumentacion CASCADE;
TRUNCATE TABLE public.ordenes CASCADE;

TRUNCATE TABLE public.clientes CASCADE;
TRUNCATE TABLE public.intermediarios CASCADE;

-- Secuencias de número interno (si existen)
DO $$ BEGIN
  IF EXISTS (SELECT 1 FROM pg_sequences WHERE schemaname = 'public' AND sequencename = 'ordenes_numero_seq') THEN
    PERFORM setval('public.ordenes_numero_seq', 1, false);
  END IF;
  IF EXISTS (SELECT 1 FROM pg_sequences WHERE schemaname = 'public' AND sequencename = 'transacciones_numero_seq') THEN
    PERFORM setval('public.transacciones_numero_seq', 1, false);
  END IF;
END $$;

-- ---------- Clientes ----------
INSERT INTO public.clientes (nombre, activo) VALUES ('Mayo', true);
INSERT INTO public.clientes (nombre, activo) VALUES ('Abudiab', true);
INSERT INTO public.clientes (nombre, activo) VALUES ('Aced', true);
INSERT INTO public.clientes (nombre, activo) VALUES ('Achi', true);
INSERT INTO public.clientes (nombre, activo) VALUES ('Adot', true);
INSERT INTO public.clientes (nombre, activo) VALUES ('Adriana', true);
INSERT INTO public.clientes (nombre, activo) VALUES ('Alfie', true);
INSERT INTO public.clientes (nombre, activo) VALUES ('Alvarito', true);
INSERT INTO public.clientes (nombre, activo) VALUES ('Aranguez', true);
INSERT INTO public.clientes (nombre, activo) VALUES ('Ari Eisen', true);
INSERT INTO public.clientes (nombre, activo) VALUES ('Arrascaeta', true);
INSERT INTO public.clientes (nombre, activo) VALUES ('Barreiro', true);
INSERT INTO public.clientes (nombre, activo) VALUES ('Blanch', true);
INSERT INTO public.clientes (nombre, activo) VALUES ('Blanco', true);
INSERT INTO public.clientes (nombre, activo) VALUES ('Buitre', true);
INSERT INTO public.clientes (nombre, activo) VALUES ('Cagnoni', true);
INSERT INTO public.clientes (nombre, activo) VALUES ('Caja Madero', true);
INSERT INTO public.clientes (nombre, activo) VALUES ('Caja Nico', true);
INSERT INTO public.clientes (nombre, activo) VALUES ('Carrera', true);
INSERT INTO public.clientes (nombre, activo) VALUES ('Casasco', true);
INSERT INTO public.clientes (nombre, activo) VALUES ('Charlie R', true);
INSERT INTO public.clientes (nombre, activo) VALUES ('cipolla', true);
INSERT INTO public.clientes (nombre, activo) VALUES ('Cora', true);
INSERT INTO public.clientes (nombre, activo) VALUES ('Crosti', true);
INSERT INTO public.clientes (nombre, activo) VALUES ('Diaz', true);
INSERT INTO public.clientes (nombre, activo) VALUES ('Doc', true);
INSERT INTO public.clientes (nombre, activo) VALUES ('Enzo Prono', true);
INSERT INTO public.clientes (nombre, activo) VALUES ('Fede ASU', true);
INSERT INTO public.clientes (nombre, activo) VALUES ('Ferrara', true);
INSERT INTO public.clientes (nombre, activo) VALUES ('Gerardo', true);
INSERT INTO public.clientes (nombre, activo) VALUES ('Gioja', true);
INSERT INTO public.clientes (nombre, activo) VALUES ('Gonza Urrus', true);
INSERT INTO public.clientes (nombre, activo) VALUES ('Gonzalito', true);
INSERT INTO public.clientes (nombre, activo) VALUES ('Guido', true);
INSERT INTO public.clientes (nombre, activo) VALUES ('Gus profe', true);
INSERT INTO public.clientes (nombre, activo) VALUES ('Kururu', true);
INSERT INTO public.clientes (nombre, activo) VALUES ('Lamela', true);
INSERT INTO public.clientes (nombre, activo) VALUES ('Lautaro', true);
INSERT INTO public.clientes (nombre, activo) VALUES ('Levi', true);
INSERT INTO public.clientes (nombre, activo) VALUES ('Mario Gomez', true);
INSERT INTO public.clientes (nombre, activo) VALUES ('Marta Di Bello', true);
INSERT INTO public.clientes (nombre, activo) VALUES ('Martegani', true);
INSERT INTO public.clientes (nombre, activo) VALUES ('Mati Florida', true);
INSERT INTO public.clientes (nombre, activo) VALUES ('Maxi Brasil', true);
INSERT INTO public.clientes (nombre, activo) VALUES ('Pablo Franck', true);
INSERT INTO public.clientes (nombre, activo) VALUES ('Pachi', true);
INSERT INTO public.clientes (nombre, activo) VALUES ('Pipi', true);
INSERT INTO public.clientes (nombre, activo) VALUES ('Raffaini', true);
INSERT INTO public.clientes (nombre, activo) VALUES ('Ranieli', true);
INSERT INTO public.clientes (nombre, activo) VALUES ('Rext', true);
INSERT INTO public.clientes (nombre, activo) VALUES ('Riesnik', true);
INSERT INTO public.clientes (nombre, activo) VALUES ('Sabrina Sir', true);
INSERT INTO public.clientes (nombre, activo) VALUES ('Seoane', true);
INSERT INTO public.clientes (nombre, activo) VALUES ('Serfin', true);
INSERT INTO public.clientes (nombre, activo) VALUES ('Sergio', true);
INSERT INTO public.clientes (nombre, activo) VALUES ('Tasco', true);
INSERT INTO public.clientes (nombre, activo) VALUES ('Tato Gomez', true);
INSERT INTO public.clientes (nombre, activo) VALUES ('Varela', true);
INSERT INTO public.clientes (nombre, activo) VALUES ('Vero Dopazo', true);
INSERT INTO public.clientes (nombre, activo) VALUES ('Vicente', true);

-- ---------- Intermediarios ----------
INSERT INTO public.intermediarios (nombre, activo) VALUES ('Fer Simon', true);
INSERT INTO public.intermediarios (nombre, activo) VALUES ('Julian', true);
INSERT INTO public.intermediarios (nombre, activo) VALUES ('Rou', true);
INSERT INTO public.intermediarios (nombre, activo) VALUES ('Wana', true);

-- ---------- Movimientos CC (saldo <> 0, moneda USD) ----------
-- Monto = saldo Excel; manual_tip y roles según signo (ver cabecera del script).

INSERT INTO public.movimientos_cuenta_corriente (cliente_id, moneda, monto, monto_usd, monto_ars, monto_eur, concepto, fecha, estado, estado_fecha, es_movimiento_manual, manual_tip_movimiento, manual_pagador_rol, manual_cobrador_rol, manual_pagador_cliente_id, manual_pagador_intermediario_id, manual_cobrador_cliente_id, manual_cobrador_intermediario_id, usuario_id, incluir_en_detalle, orden_id, transaccion_id) SELECT c.id, 'USD', 25::numeric, 25::numeric, 0::numeric, 0::numeric, 'Saldo inicial (volcado Excel) — Abudiab', public.fecha_hoy_argentina(), 'cerrado', now(), true, 'pago_pandy_entidad', 'pandy', 'cliente', NULL, NULL, c.id, NULL, (SELECT id FROM auth.users WHERE lower(trim(email)) = lower(trim('lucas.bustos.martin@gmail.com')) LIMIT 1), true, NULL, NULL FROM public.clientes c WHERE c.nombre = 'Abudiab' LIMIT 1;
INSERT INTO public.movimientos_cuenta_corriente (cliente_id, moneda, monto, monto_usd, monto_ars, monto_eur, concepto, fecha, estado, estado_fecha, es_movimiento_manual, manual_tip_movimiento, manual_pagador_rol, manual_cobrador_rol, manual_pagador_cliente_id, manual_pagador_intermediario_id, manual_cobrador_cliente_id, manual_cobrador_intermediario_id, usuario_id, incluir_en_detalle, orden_id, transaccion_id) SELECT c.id, 'USD', -4::numeric, -4::numeric, 0::numeric, 0::numeric, 'Saldo inicial (volcado Excel) — Aced', public.fecha_hoy_argentina(), 'cerrado', now(), true, 'cobro_entidad_pandy', 'cliente', 'pandy', c.id, NULL, NULL, NULL, (SELECT id FROM auth.users WHERE lower(trim(email)) = lower(trim('lucas.bustos.martin@gmail.com')) LIMIT 1), true, NULL, NULL FROM public.clientes c WHERE c.nombre = 'Aced' LIMIT 1;
INSERT INTO public.movimientos_cuenta_corriente (cliente_id, moneda, monto, monto_usd, monto_ars, monto_eur, concepto, fecha, estado, estado_fecha, es_movimiento_manual, manual_tip_movimiento, manual_pagador_rol, manual_cobrador_rol, manual_pagador_cliente_id, manual_pagador_intermediario_id, manual_cobrador_cliente_id, manual_cobrador_intermediario_id, usuario_id, incluir_en_detalle, orden_id, transaccion_id) SELECT c.id, 'USD', -65160::numeric, -65160::numeric, 0::numeric, 0::numeric, 'Saldo inicial (volcado Excel) — Alvarito', public.fecha_hoy_argentina(), 'cerrado', now(), true, 'cobro_entidad_pandy', 'cliente', 'pandy', c.id, NULL, NULL, NULL, (SELECT id FROM auth.users WHERE lower(trim(email)) = lower(trim('lucas.bustos.martin@gmail.com')) LIMIT 1), true, NULL, NULL FROM public.clientes c WHERE c.nombre = 'Alvarito' LIMIT 1;
INSERT INTO public.movimientos_cuenta_corriente (cliente_id, moneda, monto, monto_usd, monto_ars, monto_eur, concepto, fecha, estado, estado_fecha, es_movimiento_manual, manual_tip_movimiento, manual_pagador_rol, manual_cobrador_rol, manual_pagador_cliente_id, manual_pagador_intermediario_id, manual_cobrador_cliente_id, manual_cobrador_intermediario_id, usuario_id, incluir_en_detalle, orden_id, transaccion_id) SELECT c.id, 'USD', 3013::numeric, 3013::numeric, 0::numeric, 0::numeric, 'Saldo inicial (volcado Excel) — Aranguez', public.fecha_hoy_argentina(), 'cerrado', now(), true, 'pago_pandy_entidad', 'pandy', 'cliente', NULL, NULL, c.id, NULL, (SELECT id FROM auth.users WHERE lower(trim(email)) = lower(trim('lucas.bustos.martin@gmail.com')) LIMIT 1), true, NULL, NULL FROM public.clientes c WHERE c.nombre = 'Aranguez' LIMIT 1;
INSERT INTO public.movimientos_cuenta_corriente (cliente_id, moneda, monto, monto_usd, monto_ars, monto_eur, concepto, fecha, estado, estado_fecha, es_movimiento_manual, manual_tip_movimiento, manual_pagador_rol, manual_cobrador_rol, manual_pagador_cliente_id, manual_pagador_intermediario_id, manual_cobrador_cliente_id, manual_cobrador_intermediario_id, usuario_id, incluir_en_detalle, orden_id, transaccion_id) SELECT c.id, 'USD', -581::numeric, -581::numeric, 0::numeric, 0::numeric, 'Saldo inicial (volcado Excel) — Barreiro', public.fecha_hoy_argentina(), 'cerrado', now(), true, 'cobro_entidad_pandy', 'cliente', 'pandy', c.id, NULL, NULL, NULL, (SELECT id FROM auth.users WHERE lower(trim(email)) = lower(trim('lucas.bustos.martin@gmail.com')) LIMIT 1), true, NULL, NULL FROM public.clientes c WHERE c.nombre = 'Barreiro' LIMIT 1;
INSERT INTO public.movimientos_cuenta_corriente (cliente_id, moneda, monto, monto_usd, monto_ars, monto_eur, concepto, fecha, estado, estado_fecha, es_movimiento_manual, manual_tip_movimiento, manual_pagador_rol, manual_cobrador_rol, manual_pagador_cliente_id, manual_pagador_intermediario_id, manual_cobrador_cliente_id, manual_cobrador_intermediario_id, usuario_id, incluir_en_detalle, orden_id, transaccion_id) SELECT c.id, 'USD', 5545::numeric, 5545::numeric, 0::numeric, 0::numeric, 'Saldo inicial (volcado Excel) — Blanco', public.fecha_hoy_argentina(), 'cerrado', now(), true, 'pago_pandy_entidad', 'pandy', 'cliente', NULL, NULL, c.id, NULL, (SELECT id FROM auth.users WHERE lower(trim(email)) = lower(trim('lucas.bustos.martin@gmail.com')) LIMIT 1), true, NULL, NULL FROM public.clientes c WHERE c.nombre = 'Blanco' LIMIT 1;
INSERT INTO public.movimientos_cuenta_corriente (cliente_id, moneda, monto, monto_usd, monto_ars, monto_eur, concepto, fecha, estado, estado_fecha, es_movimiento_manual, manual_tip_movimiento, manual_pagador_rol, manual_cobrador_rol, manual_pagador_cliente_id, manual_pagador_intermediario_id, manual_cobrador_cliente_id, manual_cobrador_intermediario_id, usuario_id, incluir_en_detalle, orden_id, transaccion_id) SELECT c.id, 'USD', 3000::numeric, 3000::numeric, 0::numeric, 0::numeric, 'Saldo inicial (volcado Excel) — Cagnoni', public.fecha_hoy_argentina(), 'cerrado', now(), true, 'pago_pandy_entidad', 'pandy', 'cliente', NULL, NULL, c.id, NULL, (SELECT id FROM auth.users WHERE lower(trim(email)) = lower(trim('lucas.bustos.martin@gmail.com')) LIMIT 1), true, NULL, NULL FROM public.clientes c WHERE c.nombre = 'Cagnoni' LIMIT 1;
INSERT INTO public.movimientos_cuenta_corriente (cliente_id, moneda, monto, monto_usd, monto_ars, monto_eur, concepto, fecha, estado, estado_fecha, es_movimiento_manual, manual_tip_movimiento, manual_pagador_rol, manual_cobrador_rol, manual_pagador_cliente_id, manual_pagador_intermediario_id, manual_cobrador_cliente_id, manual_cobrador_intermediario_id, usuario_id, incluir_en_detalle, orden_id, transaccion_id) SELECT c.id, 'USD', -300::numeric, -300::numeric, 0::numeric, 0::numeric, 'Saldo inicial (volcado Excel) — Casasco', public.fecha_hoy_argentina(), 'cerrado', now(), true, 'cobro_entidad_pandy', 'cliente', 'pandy', c.id, NULL, NULL, NULL, (SELECT id FROM auth.users WHERE lower(trim(email)) = lower(trim('lucas.bustos.martin@gmail.com')) LIMIT 1), true, NULL, NULL FROM public.clientes c WHERE c.nombre = 'Casasco' LIMIT 1;
INSERT INTO public.movimientos_cuenta_corriente (cliente_id, moneda, monto, monto_usd, monto_ars, monto_eur, concepto, fecha, estado, estado_fecha, es_movimiento_manual, manual_tip_movimiento, manual_pagador_rol, manual_cobrador_rol, manual_pagador_cliente_id, manual_pagador_intermediario_id, manual_cobrador_cliente_id, manual_cobrador_intermediario_id, usuario_id, incluir_en_detalle, orden_id, transaccion_id) SELECT c.id, 'USD', 5::numeric, 5::numeric, 0::numeric, 0::numeric, 'Saldo inicial (volcado Excel) — Fede ASU', public.fecha_hoy_argentina(), 'cerrado', now(), true, 'pago_pandy_entidad', 'pandy', 'cliente', NULL, NULL, c.id, NULL, (SELECT id FROM auth.users WHERE lower(trim(email)) = lower(trim('lucas.bustos.martin@gmail.com')) LIMIT 1), true, NULL, NULL FROM public.clientes c WHERE c.nombre = 'Fede ASU' LIMIT 1;
INSERT INTO public.movimientos_cuenta_corriente (cliente_id, moneda, monto, monto_usd, monto_ars, monto_eur, concepto, fecha, estado, estado_fecha, es_movimiento_manual, manual_tip_movimiento, manual_pagador_rol, manual_cobrador_rol, manual_pagador_cliente_id, manual_pagador_intermediario_id, manual_cobrador_cliente_id, manual_cobrador_intermediario_id, usuario_id, incluir_en_detalle, orden_id, transaccion_id) SELECT c.id, 'USD', -3215::numeric, -3215::numeric, 0::numeric, 0::numeric, 'Saldo inicial (volcado Excel) — Gerardo', public.fecha_hoy_argentina(), 'cerrado', now(), true, 'cobro_entidad_pandy', 'cliente', 'pandy', c.id, NULL, NULL, NULL, (SELECT id FROM auth.users WHERE lower(trim(email)) = lower(trim('lucas.bustos.martin@gmail.com')) LIMIT 1), true, NULL, NULL FROM public.clientes c WHERE c.nombre = 'Gerardo' LIMIT 1;
INSERT INTO public.movimientos_cuenta_corriente (cliente_id, moneda, monto, monto_usd, monto_ars, monto_eur, concepto, fecha, estado, estado_fecha, es_movimiento_manual, manual_tip_movimiento, manual_pagador_rol, manual_cobrador_rol, manual_pagador_cliente_id, manual_pagador_intermediario_id, manual_cobrador_cliente_id, manual_cobrador_intermediario_id, usuario_id, incluir_en_detalle, orden_id, transaccion_id) SELECT c.id, 'USD', 9611::numeric, 9611::numeric, 0::numeric, 0::numeric, 'Saldo inicial (volcado Excel) — Gonza Urrus', public.fecha_hoy_argentina(), 'cerrado', now(), true, 'pago_pandy_entidad', 'pandy', 'cliente', NULL, NULL, c.id, NULL, (SELECT id FROM auth.users WHERE lower(trim(email)) = lower(trim('lucas.bustos.martin@gmail.com')) LIMIT 1), true, NULL, NULL FROM public.clientes c WHERE c.nombre = 'Gonza Urrus' LIMIT 1;
INSERT INTO public.movimientos_cuenta_corriente (cliente_id, moneda, monto, monto_usd, monto_ars, monto_eur, concepto, fecha, estado, estado_fecha, es_movimiento_manual, manual_tip_movimiento, manual_pagador_rol, manual_cobrador_rol, manual_pagador_cliente_id, manual_pagador_intermediario_id, manual_cobrador_cliente_id, manual_cobrador_intermediario_id, usuario_id, incluir_en_detalle, orden_id, transaccion_id) SELECT c.id, 'USD', 4500::numeric, 4500::numeric, 0::numeric, 0::numeric, 'Saldo inicial (volcado Excel) — Gonzalito', public.fecha_hoy_argentina(), 'cerrado', now(), true, 'pago_pandy_entidad', 'pandy', 'cliente', NULL, NULL, c.id, NULL, (SELECT id FROM auth.users WHERE lower(trim(email)) = lower(trim('lucas.bustos.martin@gmail.com')) LIMIT 1), true, NULL, NULL FROM public.clientes c WHERE c.nombre = 'Gonzalito' LIMIT 1;
INSERT INTO public.movimientos_cuenta_corriente (cliente_id, moneda, monto, monto_usd, monto_ars, monto_eur, concepto, fecha, estado, estado_fecha, es_movimiento_manual, manual_tip_movimiento, manual_pagador_rol, manual_cobrador_rol, manual_pagador_cliente_id, manual_pagador_intermediario_id, manual_cobrador_cliente_id, manual_cobrador_intermediario_id, usuario_id, incluir_en_detalle, orden_id, transaccion_id) SELECT c.id, 'USD', -21704::numeric, -21704::numeric, 0::numeric, 0::numeric, 'Saldo inicial (volcado Excel) — Guido', public.fecha_hoy_argentina(), 'cerrado', now(), true, 'cobro_entidad_pandy', 'cliente', 'pandy', c.id, NULL, NULL, NULL, (SELECT id FROM auth.users WHERE lower(trim(email)) = lower(trim('lucas.bustos.martin@gmail.com')) LIMIT 1), true, NULL, NULL FROM public.clientes c WHERE c.nombre = 'Guido' LIMIT 1;
INSERT INTO public.movimientos_cuenta_corriente (cliente_id, moneda, monto, monto_usd, monto_ars, monto_eur, concepto, fecha, estado, estado_fecha, es_movimiento_manual, manual_tip_movimiento, manual_pagador_rol, manual_cobrador_rol, manual_pagador_cliente_id, manual_pagador_intermediario_id, manual_cobrador_cliente_id, manual_cobrador_intermediario_id, usuario_id, incluir_en_detalle, orden_id, transaccion_id) SELECT c.id, 'USD', 4500::numeric, 4500::numeric, 0::numeric, 0::numeric, 'Saldo inicial (volcado Excel) — Gus profe', public.fecha_hoy_argentina(), 'cerrado', now(), true, 'pago_pandy_entidad', 'pandy', 'cliente', NULL, NULL, c.id, NULL, (SELECT id FROM auth.users WHERE lower(trim(email)) = lower(trim('lucas.bustos.martin@gmail.com')) LIMIT 1), true, NULL, NULL FROM public.clientes c WHERE c.nombre = 'Gus profe' LIMIT 1;
INSERT INTO public.movimientos_cuenta_corriente (cliente_id, moneda, monto, monto_usd, monto_ars, monto_eur, concepto, fecha, estado, estado_fecha, es_movimiento_manual, manual_tip_movimiento, manual_pagador_rol, manual_cobrador_rol, manual_pagador_cliente_id, manual_pagador_intermediario_id, manual_cobrador_cliente_id, manual_cobrador_intermediario_id, usuario_id, incluir_en_detalle, orden_id, transaccion_id) SELECT c.id, 'USD', -200000::numeric, -200000::numeric, 0::numeric, 0::numeric, 'Saldo inicial (volcado Excel) — Lautaro', public.fecha_hoy_argentina(), 'cerrado', now(), true, 'cobro_entidad_pandy', 'cliente', 'pandy', c.id, NULL, NULL, NULL, (SELECT id FROM auth.users WHERE lower(trim(email)) = lower(trim('lucas.bustos.martin@gmail.com')) LIMIT 1), true, NULL, NULL FROM public.clientes c WHERE c.nombre = 'Lautaro' LIMIT 1;
INSERT INTO public.movimientos_cuenta_corriente (cliente_id, moneda, monto, monto_usd, monto_ars, monto_eur, concepto, fecha, estado, estado_fecha, es_movimiento_manual, manual_tip_movimiento, manual_pagador_rol, manual_cobrador_rol, manual_pagador_cliente_id, manual_pagador_intermediario_id, manual_cobrador_cliente_id, manual_cobrador_intermediario_id, usuario_id, incluir_en_detalle, orden_id, transaccion_id) SELECT c.id, 'USD', -1836::numeric, -1836::numeric, 0::numeric, 0::numeric, 'Saldo inicial (volcado Excel) — Levi', public.fecha_hoy_argentina(), 'cerrado', now(), true, 'cobro_entidad_pandy', 'cliente', 'pandy', c.id, NULL, NULL, NULL, (SELECT id FROM auth.users WHERE lower(trim(email)) = lower(trim('lucas.bustos.martin@gmail.com')) LIMIT 1), true, NULL, NULL FROM public.clientes c WHERE c.nombre = 'Levi' LIMIT 1;
INSERT INTO public.movimientos_cuenta_corriente (cliente_id, moneda, monto, monto_usd, monto_ars, monto_eur, concepto, fecha, estado, estado_fecha, es_movimiento_manual, manual_tip_movimiento, manual_pagador_rol, manual_cobrador_rol, manual_pagador_cliente_id, manual_pagador_intermediario_id, manual_cobrador_cliente_id, manual_cobrador_intermediario_id, usuario_id, incluir_en_detalle, orden_id, transaccion_id) SELECT c.id, 'USD', 5000::numeric, 5000::numeric, 0::numeric, 0::numeric, 'Saldo inicial (volcado Excel) — Mario Gomez', public.fecha_hoy_argentina(), 'cerrado', now(), true, 'pago_pandy_entidad', 'pandy', 'cliente', NULL, NULL, c.id, NULL, (SELECT id FROM auth.users WHERE lower(trim(email)) = lower(trim('lucas.bustos.martin@gmail.com')) LIMIT 1), true, NULL, NULL FROM public.clientes c WHERE c.nombre = 'Mario Gomez' LIMIT 1;
INSERT INTO public.movimientos_cuenta_corriente (cliente_id, moneda, monto, monto_usd, monto_ars, monto_eur, concepto, fecha, estado, estado_fecha, es_movimiento_manual, manual_tip_movimiento, manual_pagador_rol, manual_cobrador_rol, manual_pagador_cliente_id, manual_pagador_intermediario_id, manual_cobrador_cliente_id, manual_cobrador_intermediario_id, usuario_id, incluir_en_detalle, orden_id, transaccion_id) SELECT c.id, 'USD', -2000::numeric, -2000::numeric, 0::numeric, 0::numeric, 'Saldo inicial (volcado Excel) — Martegani', public.fecha_hoy_argentina(), 'cerrado', now(), true, 'cobro_entidad_pandy', 'cliente', 'pandy', c.id, NULL, NULL, NULL, (SELECT id FROM auth.users WHERE lower(trim(email)) = lower(trim('lucas.bustos.martin@gmail.com')) LIMIT 1), true, NULL, NULL FROM public.clientes c WHERE c.nombre = 'Martegani' LIMIT 1;
INSERT INTO public.movimientos_cuenta_corriente (cliente_id, moneda, monto, monto_usd, monto_ars, monto_eur, concepto, fecha, estado, estado_fecha, es_movimiento_manual, manual_tip_movimiento, manual_pagador_rol, manual_cobrador_rol, manual_pagador_cliente_id, manual_pagador_intermediario_id, manual_cobrador_cliente_id, manual_cobrador_intermediario_id, usuario_id, incluir_en_detalle, orden_id, transaccion_id) SELECT c.id, 'USD', 43209::numeric, 43209::numeric, 0::numeric, 0::numeric, 'Saldo inicial (volcado Excel) — Mati Florida', public.fecha_hoy_argentina(), 'cerrado', now(), true, 'pago_pandy_entidad', 'pandy', 'cliente', NULL, NULL, c.id, NULL, (SELECT id FROM auth.users WHERE lower(trim(email)) = lower(trim('lucas.bustos.martin@gmail.com')) LIMIT 1), true, NULL, NULL FROM public.clientes c WHERE c.nombre = 'Mati Florida' LIMIT 1;
INSERT INTO public.movimientos_cuenta_corriente (cliente_id, moneda, monto, monto_usd, monto_ars, monto_eur, concepto, fecha, estado, estado_fecha, es_movimiento_manual, manual_tip_movimiento, manual_pagador_rol, manual_cobrador_rol, manual_pagador_cliente_id, manual_pagador_intermediario_id, manual_cobrador_cliente_id, manual_cobrador_intermediario_id, usuario_id, incluir_en_detalle, orden_id, transaccion_id) SELECT c.id, 'USD', 50000::numeric, 50000::numeric, 0::numeric, 0::numeric, 'Saldo inicial (volcado Excel) — Pachi', public.fecha_hoy_argentina(), 'cerrado', now(), true, 'pago_pandy_entidad', 'pandy', 'cliente', NULL, NULL, c.id, NULL, (SELECT id FROM auth.users WHERE lower(trim(email)) = lower(trim('lucas.bustos.martin@gmail.com')) LIMIT 1), true, NULL, NULL FROM public.clientes c WHERE c.nombre = 'Pachi' LIMIT 1;
INSERT INTO public.movimientos_cuenta_corriente (cliente_id, moneda, monto, monto_usd, monto_ars, monto_eur, concepto, fecha, estado, estado_fecha, es_movimiento_manual, manual_tip_movimiento, manual_pagador_rol, manual_cobrador_rol, manual_pagador_cliente_id, manual_pagador_intermediario_id, manual_cobrador_cliente_id, manual_cobrador_intermediario_id, usuario_id, incluir_en_detalle, orden_id, transaccion_id) SELECT c.id, 'USD', -4627::numeric, -4627::numeric, 0::numeric, 0::numeric, 'Saldo inicial (volcado Excel) — Pipi', public.fecha_hoy_argentina(), 'cerrado', now(), true, 'cobro_entidad_pandy', 'cliente', 'pandy', c.id, NULL, NULL, NULL, (SELECT id FROM auth.users WHERE lower(trim(email)) = lower(trim('lucas.bustos.martin@gmail.com')) LIMIT 1), true, NULL, NULL FROM public.clientes c WHERE c.nombre = 'Pipi' LIMIT 1;
INSERT INTO public.movimientos_cuenta_corriente (cliente_id, moneda, monto, monto_usd, monto_ars, monto_eur, concepto, fecha, estado, estado_fecha, es_movimiento_manual, manual_tip_movimiento, manual_pagador_rol, manual_cobrador_rol, manual_pagador_cliente_id, manual_pagador_intermediario_id, manual_cobrador_cliente_id, manual_cobrador_intermediario_id, usuario_id, incluir_en_detalle, orden_id, transaccion_id) SELECT c.id, 'USD', 1348::numeric, 1348::numeric, 0::numeric, 0::numeric, 'Saldo inicial (volcado Excel) — Seoane', public.fecha_hoy_argentina(), 'cerrado', now(), true, 'pago_pandy_entidad', 'pandy', 'cliente', NULL, NULL, c.id, NULL, (SELECT id FROM auth.users WHERE lower(trim(email)) = lower(trim('lucas.bustos.martin@gmail.com')) LIMIT 1), true, NULL, NULL FROM public.clientes c WHERE c.nombre = 'Seoane' LIMIT 1;
INSERT INTO public.movimientos_cuenta_corriente (cliente_id, moneda, monto, monto_usd, monto_ars, monto_eur, concepto, fecha, estado, estado_fecha, es_movimiento_manual, manual_tip_movimiento, manual_pagador_rol, manual_cobrador_rol, manual_pagador_cliente_id, manual_pagador_intermediario_id, manual_cobrador_cliente_id, manual_cobrador_intermediario_id, usuario_id, incluir_en_detalle, orden_id, transaccion_id) SELECT c.id, 'USD', 900::numeric, 900::numeric, 0::numeric, 0::numeric, 'Saldo inicial (volcado Excel) — Sergio', public.fecha_hoy_argentina(), 'cerrado', now(), true, 'pago_pandy_entidad', 'pandy', 'cliente', NULL, NULL, c.id, NULL, (SELECT id FROM auth.users WHERE lower(trim(email)) = lower(trim('lucas.bustos.martin@gmail.com')) LIMIT 1), true, NULL, NULL FROM public.clientes c WHERE c.nombre = 'Sergio' LIMIT 1;
INSERT INTO public.movimientos_cuenta_corriente (cliente_id, moneda, monto, monto_usd, monto_ars, monto_eur, concepto, fecha, estado, estado_fecha, es_movimiento_manual, manual_tip_movimiento, manual_pagador_rol, manual_cobrador_rol, manual_pagador_cliente_id, manual_pagador_intermediario_id, manual_cobrador_cliente_id, manual_cobrador_intermediario_id, usuario_id, incluir_en_detalle, orden_id, transaccion_id) SELECT c.id, 'USD', -1295::numeric, -1295::numeric, 0::numeric, 0::numeric, 'Saldo inicial (volcado Excel) — Varela', public.fecha_hoy_argentina(), 'cerrado', now(), true, 'cobro_entidad_pandy', 'cliente', 'pandy', c.id, NULL, NULL, NULL, (SELECT id FROM auth.users WHERE lower(trim(email)) = lower(trim('lucas.bustos.martin@gmail.com')) LIMIT 1), true, NULL, NULL FROM public.clientes c WHERE c.nombre = 'Varela' LIMIT 1;
INSERT INTO public.movimientos_cuenta_corriente (cliente_id, moneda, monto, monto_usd, monto_ars, monto_eur, concepto, fecha, estado, estado_fecha, es_movimiento_manual, manual_tip_movimiento, manual_pagador_rol, manual_cobrador_rol, manual_pagador_cliente_id, manual_pagador_intermediario_id, manual_cobrador_cliente_id, manual_cobrador_intermediario_id, usuario_id, incluir_en_detalle, orden_id, transaccion_id) SELECT c.id, 'USD', 2::numeric, 2::numeric, 0::numeric, 0::numeric, 'Saldo inicial (volcado Excel) — Vero Dopazo', public.fecha_hoy_argentina(), 'cerrado', now(), true, 'pago_pandy_entidad', 'pandy', 'cliente', NULL, NULL, c.id, NULL, (SELECT id FROM auth.users WHERE lower(trim(email)) = lower(trim('lucas.bustos.martin@gmail.com')) LIMIT 1), true, NULL, NULL FROM public.clientes c WHERE c.nombre = 'Vero Dopazo' LIMIT 1;
INSERT INTO public.movimientos_cuenta_corriente (cliente_id, moneda, monto, monto_usd, monto_ars, monto_eur, concepto, fecha, estado, estado_fecha, es_movimiento_manual, manual_tip_movimiento, manual_pagador_rol, manual_cobrador_rol, manual_pagador_cliente_id, manual_pagador_intermediario_id, manual_cobrador_cliente_id, manual_cobrador_intermediario_id, usuario_id, incluir_en_detalle, orden_id, transaccion_id) SELECT c.id, 'USD', 1000::numeric, 1000::numeric, 0::numeric, 0::numeric, 'Saldo inicial (volcado Excel) — Vicente', public.fecha_hoy_argentina(), 'cerrado', now(), true, 'pago_pandy_entidad', 'pandy', 'cliente', NULL, NULL, c.id, NULL, (SELECT id FROM auth.users WHERE lower(trim(email)) = lower(trim('lucas.bustos.martin@gmail.com')) LIMIT 1), true, NULL, NULL FROM public.clientes c WHERE c.nombre = 'Vicente' LIMIT 1;
INSERT INTO public.movimientos_cuenta_corriente_intermediario (intermediario_id, moneda, monto, monto_usd, monto_ars, monto_eur, concepto, fecha, estado, estado_fecha, es_movimiento_manual, manual_tip_movimiento, manual_pagador_rol, manual_cobrador_rol, manual_pagador_cliente_id, manual_pagador_intermediario_id, manual_cobrador_cliente_id, manual_cobrador_intermediario_id, usuario_id, incluir_en_detalle, orden_id, transaccion_id) SELECT i.id, 'USD', -1::numeric, -1::numeric, 0::numeric, 0::numeric, 'Saldo inicial (volcado Excel) — Fer Simon', public.fecha_hoy_argentina(), 'cerrado', now(), true, 'cobro_entidad_pandy', 'intermediario', 'pandy', NULL, i.id, NULL, NULL, (SELECT id FROM auth.users WHERE lower(trim(email)) = lower(trim('lucas.bustos.martin@gmail.com')) LIMIT 1), true, NULL, NULL FROM public.intermediarios i WHERE i.nombre = 'Fer Simon' LIMIT 1;
INSERT INTO public.movimientos_cuenta_corriente_intermediario (intermediario_id, moneda, monto, monto_usd, monto_ars, monto_eur, concepto, fecha, estado, estado_fecha, es_movimiento_manual, manual_tip_movimiento, manual_pagador_rol, manual_cobrador_rol, manual_pagador_cliente_id, manual_pagador_intermediario_id, manual_cobrador_cliente_id, manual_cobrador_intermediario_id, usuario_id, incluir_en_detalle, orden_id, transaccion_id) SELECT i.id, 'USD', 468.15::numeric, 468.15::numeric, 0::numeric, 0::numeric, 'Saldo inicial (volcado Excel) — Julian', public.fecha_hoy_argentina(), 'cerrado', now(), true, 'pago_pandy_entidad', 'pandy', 'intermediario', NULL, NULL, NULL, i.id, (SELECT id FROM auth.users WHERE lower(trim(email)) = lower(trim('lucas.bustos.martin@gmail.com')) LIMIT 1), true, NULL, NULL FROM public.intermediarios i WHERE i.nombre = 'Julian' LIMIT 1;
INSERT INTO public.movimientos_cuenta_corriente_intermediario (intermediario_id, moneda, monto, monto_usd, monto_ars, monto_eur, concepto, fecha, estado, estado_fecha, es_movimiento_manual, manual_tip_movimiento, manual_pagador_rol, manual_cobrador_rol, manual_pagador_cliente_id, manual_pagador_intermediario_id, manual_cobrador_cliente_id, manual_cobrador_intermediario_id, usuario_id, incluir_en_detalle, orden_id, transaccion_id) SELECT i.id, 'USD', -272698.98::numeric, -272698.98::numeric, 0::numeric, 0::numeric, 'Saldo inicial (volcado Excel) — Rou', public.fecha_hoy_argentina(), 'cerrado', now(), true, 'cobro_entidad_pandy', 'intermediario', 'pandy', NULL, i.id, NULL, NULL, (SELECT id FROM auth.users WHERE lower(trim(email)) = lower(trim('lucas.bustos.martin@gmail.com')) LIMIT 1), true, NULL, NULL FROM public.intermediarios i WHERE i.nombre = 'Rou' LIMIT 1;

COMMIT;
